#include "mapreduce.h"

int main(int argc, char *argv[]) {

	if(argc < 4) {
		printf("Less number of arguments.\n");
		printf("./mapreduce #mappers #reducers inputFile\n");
		exit(0);
	}

	// ###### DO NOT REMOVE ######
	int nMappers 	= strtol(argv[1], NULL, 10);
	int nReducers 	= strtol(argv[2], NULL, 10);
	char *inputFile = argv[3];

	// ###### DO NOT REMOVE ######
	bookeepingCode();

	// ###### DO NOT REMOVE ######
	pid_t pid = fork();
	if(pid == 0) {
		//sends chunks of data to the mappers in RR fashion
		sendChunkData(inputFile, nMappers);
		exit(0);
	}
	else if(pid < 0) {
		printf("Failure creating child process %d", errno);	
	}
	sleep(1);


	// spawns child processes and runs mapper executable using execl
	// iterates an integer i until it equals the number of mappers
	// runs mapper for each iteration
	int i;
	pid_t child_pids[nMappers];
	char* idM = (char*)malloc(sizeof(char)*5);
	for (i = 0; i<nMappers;i++) {
		child_pids[i] = fork();
		if(child_pids[i]==0) {
			sprintf(idM, "%d", i + 1);
			execl("./mapper", "./mapper", idM, (char*)NULL);
		}
		else if(child_pids[i] < 0) {
		printf("Failure creating mapper child process %d", errno);	
		}
	}
	
	// waits for all mapper children to complete execution
   for (i=0; i<nMappers; i++) {
		wait(NULL);
	}

	// ###### DO NOT REMOVE ######
   // sends the word.txt files generated by mapper to reducer based on a hash function
	pid = fork();
	if(pid == 0) {
		shuffle(nMappers, nReducers);
		exit(0);
	}
	else if(pid < 0) {
		printf("Failure creating child process %d", errno);	
	}
	sleep(1);

	// spawns child processes and runs reducer executable using execl
	// iterates an integer j until it equals the number of reducers
	// runs reducer for each iteration
	int j;
	pid_t child_pids2[nReducers];
	char* idR = (char*)malloc(sizeof(char)*5);
	for (j = 0; j<nReducers;j++) {
		child_pids2[j] = fork();
		if (child_pids2[j]==0) {
			sprintf(idR, "%d", j + 1);
			execl("./reducer", "./reducer", idR, (char*)NULL);
		}
		else if(child_pids2[j] < 0) {
		printf("Failure creating reducer child process %d", errno);	
		}
	}
	
	// waits for all reducer children to complete execution
	for (j=0; j<nReducers; j++) {
		wait(NULL);
	}
	return 0;
}
