#include "mapreduce.h"

int main(int argc, char *argv[]) {

	if(argc < 4) {
		printf("Less number of arguments.\n");
		printf("./mapreduce #mappers #reducers inputFile\n");
		exit(0);
	}

	// ###### DO NOT REMOVE ######
	int nMappers 	= strtol(argv[1], NULL, 10);
	int nReducers 	= strtol(argv[2], NULL, 10);
	char *inputFile = argv[3];

	// ###### DO NOT REMOVE ######
	bookeepingCode();

	// ###### DO NOT REMOVE ######
	pid_t pid = fork();
	if(pid == 0){
		//send chunks of data to the mappers in RR fashion
		sendChunkData(inputFile, nMappers);
		exit(0);
	}
	sleep(1);


	// To do
	// spawn mappers processes and run 'mapper' executable using exec
	int i;
	pid_t child_pids[nMappers];
	char* idM = (char*)malloc(sizeof(char)*5);
	for (i = 0; i<nMappers;i++) {
		child_pids[i] = fork();
		if(child_pids[i]==0) {
			sprintf(idM, "%d", i + 1);
			execl("./mapper", "./mapper", idM, (char*)NULL);
		}
	}
	// To do
	// wait for all children to complete execution
  for (i=0; i<nMappers; i++) {
		wait(NULL);
	}

	// ###### DO NOT REMOVE ######
    // shuffle sends the word.txt files generated by mapper
    // to reducer based on a hash function
	pid = fork();
	if(pid == 0){
		shuffle(nMappers, nReducers);
		exit(0);
	}
	sleep(1);


	// To do
	// spawn reducer processes and run 'reducer' executable using exec
	int j;
	pid_t child_pids2[nReducers];
	char* idR = (char*)malloc(sizeof(char)*5);
	for (j = 0; j<nReducers;j++) {
		child_pids2[j] = fork();
		if (child_pids2[j]==0) {
			sprintf(idR, "%d", j + 1);
			execl("./reducer", "./reducer", idR, (char*)NULL);
		}
	}
	// To do
	// wait for all children to complete execution
	for (j=0; j<nReducers; j++) {
		wait(NULL);
	}
	return 0;
}
