/*#include "mapreduce.h"


void spawnMapper(nMappers){
		MapperCount = nMappers;		
		while(MapperCount > 0){
			pid_t pid = fork();
			if(pid == 0){
				execvp(./mapper MapperCount);
				exit(0);
			}
	// To do
	// wait for all children to complete execution
			else if(pid > 0){
				sleep(2);
				waitpid(pid, NULL, 0);
   		}
   		else {
		   	printf("Failure creating child process %d", errno);
   		}
   		MapperCount -= 1;	
		}	
}

void spawnReducers(nReducers){
		ReducerCount = nReducers;		
		while(ReducerCount > 0){
			pid_t pid = fork();
			if(pid == 0){
				execvp(./reducer ReducerCount);
				exit(0);
			}
	// To do
	// wait for all children to complete execution
			else if(pid > 0){
				sleep(2);
				waitpid(pid, NULL, 0);
   		}
   		else {
		   	printf("Failure creating child process %d", errno);
   		}
   		ReducerCount -= 1;	
		}	
}

int main(int argc, char *argv[]) {
	
	if(argc < 4) {
		printf("Less number of arguments.\n");
		printf("./mapreduce #mappers #reducers inputFile\n");
		exit(0);
	}

	// ###### DO NOT REMOVE ######
	int nMappers 	= strtol(argv[1], NULL, 10);
	int nReducers 	= strtol(argv[2], NULL, 10);
	char *inputFile = argv[3];

	// ###### DO NOT REMOVE ######
	bookeepingCode();

	// ###### DO NOT REMOVE ######
	pid_t pid = fork();
	if(pid == 0){
		//send chunks of data to the mappers in RR fashion
		sendChunkData(inputFile, nMappers);
		exit(0);
	}
	sleep(1);


	// To do
	// spawn mappers processes and run 'mapper' executable using exec
	// wait for all children to complete execution
	spawnMapper(nMappers)
	sleep(1)


	// ###### DO NOT REMOVE ######
    // shuffle sends the word.txt files generated by mapper 
    // to reducer based on a hash function
	pid = fork();
	if(pid == 0){
		shuffle(nMappers, nReducers);
		exit(0);
	}
	sleep(1);


	// To do
	// spawn reducer processes and run 'reducer' executable using exec
	// wait for all children to complete execution
	spawnReducers(nReducers)
	sleep(1)
	

	return 0;
}*/
#include "mapreduce.h"

int main(int argc, char *argv[]) {

	if(argc < 4) {
		printf("Less number of arguments.\n");
		printf("./mapreduce #mappers #reducers inputFile\n");
		exit(0);
	}

	// ###### DO NOT REMOVE ######
	int nMappers 	= strtol(argv[1], NULL, 10);
	int nReducers 	= strtol(argv[2], NULL, 10);
	char *inputFile = argv[3];

	// ###### DO NOT REMOVE ######
	bookeepingCode();

	// ###### DO NOT REMOVE ######
	pid_t pid = fork();
	if(pid == 0){
		//send chunks of data to the mappers in RR fashion
		sendChunkData(inputFile, nMappers);
		exit(0);
	}
	sleep(1);


	// To do
	// spawn mappers processes and run 'mapper' executable using exec
	int i;
	pid_t child_pids[nMappers];
	char* idM = (char*)malloc(sizeof(char)*5);
	for (i = 0; i<nMappers;i++) {
		child_pids[i] = fork();
		if(child_pids[i]==0) {
			sprintf(idM, "%d", i + 1);
			execl("./mapper", "./mapper", idM, (char*)NULL);
		}
	}
	// To do
	// wait for all children to complete execution
  for (i=0; i<nMappers; i++) {
		wait(NULL);
	}

	// ###### DO NOT REMOVE ######
    // shuffle sends the word.txt files generated by mapper
    // to reducer based on a hash function
	pid = fork();
	if(pid == 0){
		shuffle(nMappers, nReducers);
		exit(0);
	}
	sleep(1);


	// To do
	// spawn reducer processes and run 'reducer' executable using exec
	int j;
	pid_t child_pids2[nReducers];
	char * idR[nReducers];
	for (j = 0; j<nReducers;j++) {
		if ((child_pids2[j]=fork())==0) {
			sprintf(idR[j], "%d", j);
			execl("/src/reducer", "reducer", idR[j], (char*)0);
		}
	}
	// To do
	// wait for all children to complete execution
	for (j=0; j<nReducers; j++) {
		wait(NULL);
	}
	return 0;
}
